### ISSUE TITLE
Not an issue but seeking Help with Horizontal scan

### ISSUE THREAD

**Issue by Rebehy** [mjurczyk/png-to-hex#1]
Hi,
Thanks for this awesome piece of code. I have managed to get it working however, my application requires a horizontal scan and I have realized that the code as is gives me a vertical scan.

Is it possible to amend the code to output a Horizontal scan? I am very new to this so any help would be greatly appreciated. 

Thanks in advance.

**Comment by mjurczyk** [comment]
❤️ Unexpected issue, but a welcome one.
I think it may be enough to add a 90 degrees rotation to the image before running it through the png-to-hex? It should then output horizontal lines.
